### ISSUE TITLE
Help: Unable to see the App Inbox message

### ISSUE THREAD

**Issue by majeedyaseen** [CleverTap/clevertap-ios-sdk#131]
I have created a campaign for the AppInbox and I was trying to test it in the iOS. However I am not seeing any message shown on the AppInbox VC. Rather I am getting No message(s) to show

Even in initialisation I am getting 0 counts for the below methods.
CleverTap.sharedInstance()?.getInboxMessageCount() 
CleverTap.sharedInstance()?.getInboxMessageUnreadCount() 

The project is configured since a long and  is working for other services like push, it's just AppInbox in now showing messages even the campaign is created.

Am I missing something or is there anything specific to be done, I was following this doc  [App Inbox](https://developer.clevertap.com/docs/ios#section-app-inbox)

Thanks in advance

<img width="358" alt="Screenshot 2021-06-09 at 3 17 02 PM" src="https://user-images.githubusercontent.com/30460873/121332723-c164f200-c935-11eb-81e2-6c1dd544f54d.png">

**Comment by Aditi3** [comment]
@majeedyaseen We verified the behaviour at our end and it seems to be working correctly. I'm not sure what could be the issue at your end, Hence I request raising a support ticket from the dashboard with the App Inbox Campaign link so that we can debug this further & help you resolve the issue at the earliest.

**Comment by majeedyaseen** [comment]
Sure will do, Thankyou
