### ISSUE TITLE
CleverTapSDK +[CTPreferences putObject:forKey:]

### ISSUE THREAD

**Issue by r-a-o** [CleverTap/clevertap-ios-sdk#21]
Seeing a lot of `CleverTapSDK+[CTPreferences putObject:forKey:]` crashes lately on the latest version of iOS (12.1.4)

Please find the crash log below:
[CT-crash.txt](https://github.com/CleverTap/clevertap-ios-sdk/files/2940288/CT-crash.txt)

**Comment by Aditi3** [comment]
Hey @r-a-o ,

Please check the issue #11 looks similar.

**Comment by r-a-o** [comment]
Hi @Aditi3 
I have taken a look, we don't have any KVO observers on CT preferences nor do we have any third party SDKs that would mysteriously cause a crash on calling CT preferences. 

Furthermore, it looks like the `putObject` method of `CTPreferences` class is writing preferences to APMSqliteStore (SQLite store) which is causing a crash in some write-transaction scenario. 

_This issue has only started very recently for us and is a big percentage of our app crashes now (42crashes out of 60 overall) which is very concerning to us. Would appreciate swift action in resolving the issue._

Let me know if you need any more details.

**Comment by Aditi3** [comment]
Hey @r-a-o 

I request you to check KVO observers on NSUserDefaults, not on CTPreferences.

Moreover, our SDK nowhere use APMSqliteStore to store the data. We use NSUserDefaults for storing data in the preference. 

Our SDK code is open source, you can actually take a look at `putObject` method of the `CTPreferences` class.

Additionally, to help you better here and identify why the crash has started very recently for your application I would request you to write to support@clevertap.com. So that we can look into this further.

Thanks!
