### ISSUE TITLE
No such module 'ClevertTapSDK'

### ISSUE THREAD

**Issue by therohansanap** [CleverTap/clevertap-ios-sdk#3]
In my Swift project, I use various libraries (written in Objective-C as well as Swift). To be able to use libraries written in both languages, I have to use `use_frameworks!` directive in my Podfile. If I use this directive, I am not required to use bridging header for any other library written in Objective-C. I can just use `import ModuleName` and use it.

But, when I install CleverTap SDK via Podfile and try to do `import CleverTapSDK`, Xcode is giving me error as "No such module CleverTapSDK"

**Comment by pwilkniss** [comment]
@therohansanap sorry not really following you here.  to use our objective-c framework in your swift project you just need add the bridging header, example here   https://github.com/CleverTap/clevertap-ios-sdk/blob/master/SwiftStarterProject/CleverTapSDK-Bridging-Header.h

**Comment by therohansanap** [comment]
I did add bridging header and the framework is working. No issues with that.

But generally, if I use `use_frameworks!` directive in `Podfile` then I do not need to add bridging header for Objective-C libraries. I use various libraries in my project which are written in Objective-C (eg: AFNetworking). For them, I am not required to add bridging header because I am installing them using `use_frameworks!` directive (which implies we will be using frameworks instead of static libraries).

[This article](http://www.innerexception.com/2015/05/cocoapods-useframeworks-means-bridging.html) explains how every other library written in Objective-C behaves if we integrate it in out project using Cocoapod by using `use_frameworks!` directive in it.

So, I was suggesting that adding bridging header should not be required if we are integrating the SDK as framework (not static library). Would appriciate if this change is made.

**Comment by pwilkniss** [comment]
@therohansanap thanks for the follow up.  I think the issue has to do with how CocoaPods ends up handling our pod, rather than something on our end, likely because our underlying source is already an obj-c framework.

**Comment by corporate-fun** [comment]
@pwilkniss, I'm having a similar issue. I'm trying to make use of the CleverTapSDK framework in a swift framework, but Swift frameworks can't use bridging headers. So, I've tried to include the CleverTapSDK.framework in the "Link Binary With Libraries" section under my framework's "Build Phases" settings, but it's not working. Any suggestions?

**Comment by pwilkniss** [comment]
@corporate-fun  i've attached a version of the SDK built to include a modulemap.  Are you game to try swapping it in to your project?  In your .swift files you would then just   import CleverTapSDK.  If all is well, we'll get this into the next release.
[CleverTapSDK.framework.zip](https://github.com/CleverTap/clevertap-ios-sdk/files/880832/CleverTapSDK.framework.zip)

**Comment by corporate-fun** [comment]
@pwilkniss, it appears to be working now with the attached framework -- thanks.

I only had to include the path to the framework in my "Build Settings" "Framework Search Paths", and had to add the "CoreTelephony" framework in my target's "Link Binary With Libraries" under "Build Phases", since I guess CleverTap is dependant on that framework.

This works for now, but it would be desirable to integrate CleverTap via CocoaPods, so if you don't mind to follow up with me when you have released a new version on CocoaPods with this change, that would be much appreciated.

**Comment by Ankit8946** [comment]
This is still an issue. I do not wan't to add this via bridging header.

**Comment by Aditi3** [comment]
Hey @Ankit8946 

Have you tried including `use_frameworks!` in the pod file and then build your project?

CleverTapSDK is a dynamic framework, by specifying use_frameworks! you can make CocoaPods integrate to your project via frameworks instead of static libraries.

We have added modulemap for Swift in CleverTap iOS SDK version 3.1.4 and above.

Reference Change Log: https://github.com/CleverTap/clevertap-ios-sdk/blob/master/CHANGELOG.md#version-314-june-30-2017

To help you better, I recommend you to check out our Demo Application developed in Swift: https://github.com/CleverTap/clevertap-ios-sdk/tree/master/SwiftStarter

Thanks!
