### ISSUE TITLE
Xcode 10.3 support

### ISSUE THREAD

**Issue by meirbekzt** [CleverTap/clevertap-ios-sdk#30]
Hello, are there any plans for updating support for Xcode 10.3?
Please keep me updated,

Thanks!

**Comment by LudoLibon** [comment]
Any news about Xcode 10.3 support, because it's blocking. 
OS: 10.14.5 (mojave)
Xcode : Version 10.3 (10G8)
Clevertap : 3.6.0 (install with cocoapod) 

All derived data was deleted and I alwayas encoutered the problem : 

CTCoverImageViewController~iphoneport.xib:-1: Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7fa98b579940> System content for IBCocoaTouchFramework-EightAndLater <IBScaleFactorDeviceTypeDescription: 0x7fa990c270e0> scaleFactor=2x'. These intermediate objects were non-nil

**Comment by LudoLibon** [comment]
Ok, it's not a cleverTap issue, it's due to Xcode update, problem is solved when we reboot the computer (clean workspace and delete dervied data).

So for me, you can close this issue
