### ISSUE TITLE
handleNotificationWithData

### ISSUE THREAD

**Issue by maipalr** [CleverTap/clevertap-ios-sdk#56]
handleNotificationWithData openDeepLinksInForeground: true not opening the open:url function

**Comment by maipalr** [comment]
any updates on this?

**Comment by Aditi3** [comment]
Hi @maipalr 

I am assuming that you wish to open the DeepLink when the Application receives the Push Notifications in the Foreground.

I've checked the same and It seems to be working rightly. Not sure, which configuration is missing in your Application.

I request you to share a demo project with us on support@clevertap.com where the aforementioned is not working for you? We will take a look at it.

Thank you.

**Comment by LH-Dunzo** [comment]
Hi @Aditi3 

We have different apps for Staging and Production, both of them have same url scheme `dunzo://`
We tested it our end and found out that  on production application deeplink via push notification is working as expected when the application receives the push notification as `open:url `function is called. 
But the same do not happen  for Staging application.

Thanks

**Comment by Aditi3** [comment]
Hi @LH-Dunzo 

It seems like some miss in the configuration. I'd request you to reach our support team to support@clevertap.com so that we can look into this further and assist you in solving it faster.

**Comment by atalw** [comment]
Has this been solved? If so, what was the solution?

I am facing a similar issue. `open:url` is not being invoked. `openDeepLinksInForeground` is forced set to `true` in the `handleNotificationWithData` call.

Tried debugging and this invocation to function with selector `openURL:options:completionHandler:` goes through. The link is being opened in Safari which is not the expected behaviour as there is a custom function in open:url.

![image](https://user-images.githubusercontent.com/3257091/87304052-d375bf00-c531-11ea-9f57-c346b4b96ff2.png)

**Comment by Aditi3** [comment]
Hi @atalw 

Can you try implementing the URL Schemes/ Custom deep links/ Universal links to handle internal Deeplinks?

**Comment by atalw** [comment]
Hi @Aditi3, I've already done that. The `open:url` function handles it and it works, even with Firebase.
