### ISSUE TITLE
Facebook SDK is unable to handle redirection when integrated with CleverTap SDK

### ISSUE THREAD

**Issue by anuj-rajput** [CleverTap/clevertap-ios-sdk#6]
The method `- application:openURL:sourceApplication:annotation:` doesn't hit when integrated with CleverTap SDK using `+[CleverTap autoIntegrate]`

The manual integration doesn't work as well

**Comment by pwilkniss** [comment]
@anuj-rajput 

openURL:sourceApplication: is deprecated in favor of application:openURL:options:

see https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623073-application?language=objc

when you autoIntegrate the CleverTap SDK, the OS will call your AppDelegate with  application:openURL:options: rather than openURL:sourceApplication: because the CleverTap AppDelegate proxy implements that method.

You can either:
manually integrate the CleverTap SDK - see here https://support.clevertap.com/docs/ios/getting-started.html#sdk-integration.  If you manually integrate the SDK and do not yourself implement application:openURL:options:  in your AppDelegate, the OS should call the deprecated method (this behavior is totally independent of the CleverTap SDK).
or
keep the CleverTap autoIntegration and implement your FB callback in application:openURL:options:
see this SO thread - http://stackoverflow.com/questions/33737403/fbsdkapplicationdelegate-application-openurlsourceapplicationannotation-deprec
